inherit_from:
  - https://gitlab.com/bsm/misc/raw/master/rubocop/default.yml

AllCops:
  TargetRubyVersion: "2.5"
  SuggestExtensions: false

Naming/FileName:
  Exclude:
    - "lib/bsm-models.rb"

Naming/PredicateName:
  Exclude:
    - "lib/bsm/model/has_many_serialized.rb"

Security/MarshalLoad:
  Exclude:
    - "lib/bsm/model/coders/marshal_column.rb"
