inherit_gem:
  rubocop-bsm:
    - default.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: "2.6"
  SuggestExtensions: false

Naming/FileName:
  Exclude:
    - "lib/bsm-models.rb"

Naming/PredicateName:
  Exclude:
    - "lib/bsm/model/has_many_serialized.rb"

Security/MarshalLoad:
  Exclude:
    - "lib/bsm/model/coders/marshal_column.rb"
